apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "agent.fullname" . }}-cronjob
spec:
  schedule: "{{ .Values.schedule }}"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ include "agent.serviceAccountName" . }}
          restartPolicy: OnFailure
          containers:
          - name: agent
            image: nginx
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster

            env:
            # RustFS
            - name: RUSTFS_HOST
              value: "{{ .Values.rustfs.host }}"
            - name: RUSTFS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "agent.fullname" . }}-secret
                  key: RUSTFS_ACCESS_KEY
            - name: RUSTFS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "agent.fullname" . }}-secret
                  key: RUSTFS_SECRET_KEY
            