apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "agent.fullname" . }}-cronjob
spec:
  schedule: "{{ .Values.schedule }}"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ include "agent.serviceAccountName" . }}
          restartPolicy: OnFailure
          containers:
          - name: agent
            image: nginx
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster

            env:
            # RustFS
            - name: RUSTFS_HOST
              value: "{{ .Values.rustfs.host }}"
            - name: RUSTFS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "agent.fullname" . }}-secret
                  key: RUSTFS_ACCESS_KEY
            - name: RUSTFS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "agent.fullname" . }}-secret
                  key: RUSTFS_SECRET_KEY
            # PostgreSQL
            - name: POSTGRES_HOST
              value: "{{ .Values.postgres.host }}"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "agent.fullname" . }}-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "agent.fullname" . }}-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              value: "{{ .Values.postgres.database }}"
            # GPG
            - name: GPG_PASSPHRASE
              valueFrom:
                secretKeyRef:
                  name: {{ include "agent.fullname" . }}-secret
                  key: GPG_PASSPHRASE
            # SMTP
            - name: SMTP_HOST
              value: "{{ .Values.smtp.host }}"
            - name: SMTP_PORT
              value: "{{ .Values.smtp.port }}"
            - name: SMTP_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "agent.fullname" . }}-secret
                  key: SMTP_KEY
            - name: SMTP_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "agent.fullname" . }}-secret
                  key: SMTP_SECRET
            - name: SMTP_FROM
              value: "{{ .Values.smtp.from }}"
            - name: NOTIFICATION_TO
              value: "{{ .Values.smtp.notificationTo }}"